name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        env:
        - { cc: clang, cxx: clang++ }
        - { cc: gcc, cxx: g++ }
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      run: sudo apt update && sudo apt upgrade && sudo apt install qtbase5-dev qtconnectivity5-dev
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}

  linux-qts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        qt: [ '5.9.9', '5.10.1', '5.11.3', '5.12.12', '5.13.2', '5.14.2', '5.15.2', '6.2.4', '6.3.0' ]
        env:
        - { cc: clang, cxx: clang++ }
        - { cc: gcc, cxx: g++ }
    steps:
    - uses: actions/checkout@v3
    - name: Install Tools
      run: sudo apt update && sudo apt upgrade && sudo apt install clang
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        # We include both here, because Qt 6.2+ currently needs the 'addons' prefix, while
        # earlier versions don't, and aqtinstall does not currently break on unknown modules.
        # See https://github.com/miurahr/aqtinstall/issues/333 and
        # https://github.com/jurplel/install-qt-action/issues/95
        modules: qtconnectivity addons.qtconnectivity
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}

  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macOs-latest ]
        qt: [ '5.9.9', '5.10.1', '5.11.3', '5.12.12', '5.13.2', '5.14.2', '5.15.2', '6.2.4', '6.3.0' ]
        env:
        - { cc: clang, cxx: clang++ }
        - { cc: gcc-11, cxx: g++-11 }
        exclude:
          # Exclude Qt 5.10 with GCC on MacOS. See https://bugreports.qt.io/browse/QTBUG-66585
          - qt: '5.10.1'
            env: { cc: gcc-11, cxx: g++-11 }
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        # We include both here, because Qt 6.2+ currently needs the 'addons' prefix, while
        # earlier versions don't, and aqtinstall does not currently break on unknown modules.
        # See https://github.com/miurahr/aqtinstall/issues/333 and
        # https://github.com/jurplel/install-qt-action/issues/95
        modules: qtconnectivity addons.qtconnectivity
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}

  win:
    runs-on: ${{ matrix.os }}
    defaults: { run: { shell: cmd } }
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        qt: [ '5.9.9', '5.10.1', '5.11.3', '5.12.12', '5.13.2', '5.14.2', '5.15.2', '6.2.4', '6.3.0' ]
        generator: [ 'MinGW Makefiles', 'NMake Makefiles' ]
        include:
        - { qt: '5.9.9',   arch: win32_mingw53 }
        - { qt: '5.10.1',  arch: win32_mingw53 }
        - { qt: '5.11.3',  arch: win32_mingw53 }
        - { qt: '5.12.12', arch: win64_mingw73 }
        - { qt: '5.14.2',  arch: win64_mingw73 }
        - { qt: '5.15.2',  arch: win64_mingw81 }
        - { qt: '6.2.4',   arch: win64_mingw81 }
        - { qt: '6.3.0',   arch: win64_mingw }
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt (mingw)
      if: ${{ contains(matrix.generator, 'mingw') }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        # We include both here, because Qt 6.2+ currently needs the 'addons' prefix, while
        # earlier versions don't, and aqtinstall does not currently break on unknown modules.
        # See https://github.com/miurahr/aqtinstall/issues/333 and
        # https://github.com/jurplel/install-qt-action/issues/95
        modules: qtconnectivity addons.qtconnectivity
        arch: ${{ matrix.arch }}
    - name: Install Qt (msvc)
      if: ${{ contains(matrix.generator, 'nmake') }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        # We include both here, because Qt 6.2+ currently needs the 'addons' prefix, while
        # earlier versions don't, and aqtinstall does not currently break on unknown modules.
        # See https://github.com/miurahr/aqtinstall/issues/333 and
        # https://github.com/jurplel/install-qt-action/issues/95
        modules: qtconnectivity addons.qtconnectivity
    - name: Configure MSVC
      if: ${{ contains(matrix.generator, 'nmake') }}
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -G "${{ matrix.generator }}" -S "%GITHUB_WORKSPACE%" -B "%RUNNER_TEMP%"
        cmake --build "%RUNNER_TEMP%"
    # \todo Run tests on Windows.
